### ISSUE TITLE
Zeros are being ignored for snapshot names if used at the start of the name

### ISSUE THREAD

**Issue by Selfeer** [testflows/TestFlows-Asserts#3]
Zeros are being ignored for snapshot names if used at the start of the name.

For example, if in the test scenario, we generate a snapshot with the `name="0000-12312-123212424-132"`,
```python
@TestScenario
def test(self):
    with values() as that:
        assert that(
            snapshot(
                "TestValue",
                name="0000-12312-123212424-132",
            )
        ), "Something"

Scenario(run=test)
``` 

We expect the name to be `0000-12312-123212424-132== r"""'TestValue'"""`,  but in the snapshot file, it's `_12312_123212424_132 = r"""'TestValue'"""`

**Comment by Selfeer** [comment]
Some other interesting values:

- `áéíóúñ` is replaced with  `______`

- `12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890` can't be used as a value

**Comment by vzakaznikov** [comment]
This is because currently the snapshots are stored as Python modules, where the `name` must mean Python's requirements for the variable name, and variable names in Python can't start with numbers.

The names are transformed using https://github.com/testflows/TestFlows-Asserts/blob/master/testflows/asserts/helpers.py#L29.
